name: Release Pipeline

# FLOW:
#   1. Label merged dev PR with "release" -> cherry-pick into release branch
#   2. All cherry-picks accumulate in ONE release PR to main
#   3. Merge release PR -> auto-tag + GitHub Release
#
# Version: vYY.NN (v26.01, v26.02, ...)

on:
  pull_request:
    types: [labeled, closed]
    branches: [dev, main]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to cherry-pick"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  cherry-pick:
    if: |
      (github.event_name == 'pull_request' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'release' &&
       github.event.pull_request.merged == true &&
       github.event.pull_request.base.ref == 'dev') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEVOPSBOT_APP_ID }}
          private-key: ${{ secrets.DEVOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup
        id: setup
        run: |
          git fetch --tags origin
          git fetch origin main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # --- Version ---
          PREFIX="v$(date +%y)"
          LATEST=$(git tag -l "${PREFIX}.*" | sort -V | tail -n 1)
          if [ -z "$LATEST" ]; then
            NUM=1
          else
            NUM=$(( $(echo "$LATEST" | sed "s/${PREFIX}\.//" | sed 's/^0*//') + 1 ))
          fi
          NEXT=$(printf "${PREFIX}.%02d" "$NUM")

          # --- Commit info ---
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SHA="${{ inputs.commit_sha }}"
            PR_INFO="Manual: ${SHA:0:8}"
          else
            SHA="${{ github.event.pull_request.merge_commit_sha }}"
            PR_INFO="PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          fi

          echo "next=$NEXT" >> "$GITHUB_OUTPUT"
          echo "branch=release/${NEXT}" >> "$GITHUB_OUTPUT"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "sha_short=${SHA:0:8}" >> "$GITHUB_OUTPUT"
          echo "pr_info=$PR_INFO" >> "$GITHUB_OUTPUT"
          echo "::notice::Version: $NEXT | Cherry-picking: ${SHA:0:8}"

      - name: Cherry-pick
        id: pick
        run: |
          BRANCH="${{ steps.setup.outputs.branch }}"
          SHA="${{ steps.setup.outputs.sha }}"

          # Create or checkout release branch
          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            git checkout -b "$BRANCH" "origin/$BRANCH"
          else
            git checkout -b "$BRANCH" origin/main
          fi

          # Try cherry-pick (merge commit first, then regular)
          if git cherry-pick "$SHA" -m 1 --no-edit 2>/dev/null ||
             git cherry-pick "$SHA" --no-edit 2>/dev/null; then
            echo "conflict=false" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Conflict detected"
            git cherry-pick --abort
            git commit --allow-empty -m "CONFLICT: ${{ steps.setup.outputs.pr_info }} - needs manual resolution"
            echo "conflict=true" >> "$GITHUB_OUTPUT"
          fi

          git push origin "$BRANCH"

      - name: Create or update PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          BRANCH="${{ steps.setup.outputs.branch }}"
          NEXT="${{ steps.setup.outputs.next }}"
          PR_INFO="${{ steps.setup.outputs.pr_info }}"
          SHA_SHORT="${{ steps.setup.outputs.sha_short }}"
          CONFLICT="${{ steps.pick.outputs.conflict }}"

          # Gather commits
          COMMITS=$(git log origin/main.."$BRANCH" --pretty=format:"- %s (%h)" --no-merges)
          COUNT=$(git rev-list --count origin/main.."$BRANCH" --no-merges)

          BODY="## Release ${NEXT}

          **${COUNT} change(s)** ready for production

          ### Cherry-picked commits
          ${COMMITS}

          ### After Merge
          - Auto-tag: **${NEXT}**
          - GitHub Release created
          - Branch auto-deleted

          ---
          > Add more changes by labeling dev PRs with \`release\`"

          EXISTING_PR=$(gh pr list --head "$BRANCH" --base main --json number -q '.[0].number' 2>/dev/null || true)

          if [ -n "$EXISTING_PR" ]; then
            if [ "$CONFLICT" = "true" ]; then
              ICON="CONFLICT"
            else
              ICON="OK"
            fi
            gh pr comment "$EXISTING_PR" --body "${ICON}: Cherry-picked **${PR_INFO}** (${SHA_SHORT})"
            gh pr edit "$EXISTING_PR" \
              --title "Release ${NEXT} (${COUNT} changes)" \
              --body "$BODY"
          else
            gh pr create \
              --base main --head "$BRANCH" \
              --title "Release ${NEXT} (${COUNT} change)" \
              --body "$BODY" \
              --label "release"
          fi

          # Conflict label
          if [ "$CONFLICT" = "true" ]; then
            TARGET=$(gh pr list --head "$BRANCH" --base main --json number -q '.[0].number')
            gh pr edit "$TARGET" --add-label "has-conflicts"
          fi

          # Comment on source dev PR
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RELEASE_PR=$(gh pr list --head "$BRANCH" --base main --json number -q '.[0].number')
            gh pr comment "${{ github.event.pull_request.number }}" \
              --body "Added to release PR #${RELEASE_PR} -> ${NEXT}"
          fi

  auto-tag:
    if: |
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEVOPSBOT_APP_ID }}
          private-key: ${{ secrets.DEVOPSBOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ steps.app-token.outputs.token }}

      - name: Tag, release and cleanup
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags

          BRANCH="${{ github.event.pull_request.head.ref }}"
          TAG="${BRANCH#release/}"
          PR_NUM="${{ github.event.pull_request.number }}"

          # Skip if already tagged
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "::warning::Tag $TAG exists - skipping"
            exit 0
          fi

          # Tag + Release + Comment + Cleanup
          git tag -a "$TAG" -m "Release $TAG - PR #${PR_NUM}"
          git push origin "$TAG"
          gh release create "$TAG" --title "$TAG" --generate-notes --latest
          gh pr comment "$PR_NUM" --body "Released: ${TAG} - https://github.com/${{ github.repository }}/releases/tag/${TAG}"
          gh api "repos/${{ github.repository }}/git/refs/heads/${BRANCH}" -X DELETE 2>/dev/null || true
          echo "::notice::Released $TAG"
