{{- range $name, $config := .Values.nodepools }}
{{- if $config.enabled }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $name }}
spec:
  template:
    {{- if and $config.nodeLabels $config.nodeLabels.enabled }}
    metadata:
      {{- include "karpenter.nodeLabels" (dict "name" $name "config" $config "clusterName" $.Values.clusterName) | nindent 6 }}
    {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ $name }}

      requirements:
        {{- range $config.requirements }}
        - key: {{ .key }}
          operator: {{ .operator }}
          values:
            {{- range .values }}
            - {{ . | quote }}
            {{- end }}
        {{- end }}

      {{- if and $config.taints $config.taints.enabled }}
      {{- include "karpenter.taints" (dict "name" $name "config" $config) | nindent 6 }}
      {{- end }}

  {{- if $config.limits }}
  limits:
    {{- toYaml $config.limits | nindent 4 }}
  {{- end }}

  {{- if $config.disruption }}
  disruption:
    {{- toYaml $config.disruption | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
